=== naihsienchen/portfolio/portfolio/helpdesk/xml/users.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="users">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="user" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="userid" type="xs:positiveInteger" />
							<xs:element name="username" type="xs:string" />
							<xs:element name="name">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fname" type="xs:string" />
										<xs:element name="lname" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<!-- RIMINDER to self: make a customized simple data type -->
							<xs:element name="email" type="xs:string" />
							<!-- RIMINDER to self: make a customized simple data type || can we do that for securing pswd??? -->
							<xs:element name="pswd" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="category" type="xs:string" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== naihsienchen/portfolio/portfolio/helpdesk/xml/users.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
  <user category="staff">
    <!--id should be auto-generated by the system-->
    <userid>1</userid>
    <username>admin</username>
    <name>
      <fname>Staff</fname>
      <lname>Smith</lname>
    </name>
    <email>staffsmith@test.ca</email>
    <!--make sure password is encrypted-->
    <pswd>admin@test123</pswd>
  </user>
  <user category="client">
    <userid>2</userid>
    <username>client</username>
    <name>
      <fname>Client</fname>
      <lname>Smith</lname>
    </name>
    <email>clientsmith@gmail.ca</email>
    <!--make sure password is encrypted-->
    <pswd>client@test123</pswd>
  </user>
  <user category="client">
    <userid>68</userid>
    <username>missvickie</username>
    <name>
      <fname>Vicky</fname>
      <lname>Chips</lname>
    </name>
    <email>mvickie@gmail.ca</email>
    <!--make sure password is encrypted-->
    <pswd>ccc</pswd>
  </user>
</users>
